frameworkVersion: '>=1.34.0 <2.0.0'

service: serverless-boilerplate

provider:
  name: aws
  runtime: python3.7

functions:
  hello:
    handler: functions/hello/main.handler
    events:
      - http: GET hello

package:
  exclude:
    - .env/**
    - '**/__pycache__/**'
    - .vscode/**

# plugins:
  # https://serverless.com/blog/serverless-api-gateway-domain/
  # - serverless-domain-manager
  # https://github.com/sbstjn/serverless-dynamodb-autoscaling
  # - serverless-dynamodb-autoscaling
  # https://serverless.com/blog/serverless-python-packaging/
  # - serverless-python-requirements
