frameworkVersion: ">=1.30.1 <2.0.0"

service: serverless-boilerplate

provider:
  name: aws
  runtime: python3.7

functions:
  hello:
    handler: functions/hello/main.handler
    events:
      - http: GET hello
